[package]
name = "grafeas-rust"
version = "0.1.0"
authors = ["David Rivera <david.rivera@docker.com>"]
edition = "2018"

[dependencies]
tls-api         = "0.1.*"
grpc            = "0.6.1"
protobuf        = "2.6.0"
futures         = "~0.1"
futures-cpupool = "~0.1"

[lib]
test = false
doctest = false