[package]
name = "grafeas-rust"
version = "0.1.0"
authors = ["David Rivera <david.rivera@docker.com>"]
edition = "2018"

[dependencies]
grpc            = "~0.5"
protobuf        = "~2"
futures         = "~0.1"
futures-cpupool = "~0.1"

[lib]
test = false
doctest = false